[tool.ruff]
line-length = 119
target-version = "py38"

[tool.ruff.lint]
preview = true
ignore-init-module-imports = true
extend-select = [
    "B009",
    "B010",
    "CPY",
    "E",
    "F",
    "I",
    "TID251",
    "UP",
    "W",
]
ignore = [
    "E501",
    "E741",
    "W605",
    "UP007",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401",
]
"manim_animations/*" = [
    "ALL",
]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = [
    "accelerate",
]

[tool.ruff.lint.flake8-tidy-imports.banned-api."os.getenv"]
msg = "Use os.environ instead"

[tool.ruff.lint.flake8-tidy-imports.banned-api."os.putenv"]
msg = "Use os.environ instead"

[tool.ruff.lint.flake8-tidy-imports.banned-api."os.unsetenv"]
msg = "Use os.environ instead"

[tool.ruff.format]
exclude = [
    "manim_animations/*",
]

[project]
version = "0.34.2+lineaje.1"
maintainers = [
    { name = "Lineaje DepFixer", email = "221268890+Lineaje-DepFixer@users.noreply.github.com" },
]

[project.urls]
Homepage = "https://github.com/lineaje-labs-gos/huggingface-accelerate"
Repository = "https://github.com/lineaje-labs-gos/huggingface-accelerate"
Tracker = "https://github.com/lineaje-labs-gos/huggingface-accelerate/issues"
